import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "de" | "en" | "no";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  de: {
    // Promo Banner
    "promo.starterOffer": "🎉 Starter-Plan für nur €79/Monat – Angebot gültig bis 31.12.2025!",

    // Navbar
    "nav.features": "Funktionen",
    "nav.draftOrders": "Draft Orders",
    "nav.benefits": "Vorteile",
    "nav.pricing": "Preise",
    "nav.b2b": "B2B",
    "nav.faq": "FAQ",
    "nav.contact": "Kontakt",
    "nav.bookDemo": "Demo buchen",

    // Hero
    "hero.badge": "Community Commerce Engine",
    "hero.headline1": "Reservieren.",
    "hero.headline2": "Sammeln.",
    "hero.headline3": "Bezahlen.",
    "hero.subheadline": "Maximale Verkäufe. Minimaler Aufwand.",
    "hero.description1": "Egal ob Live-Stream, WhatsApp-Story oder Sammelaktion –",
    "hero.description1Bold": " ein System, ein Bestand, kein Chaos.",
    "hero.description2": "LiveDealz verbindet Live-Shopping, Stories und Sammelaktionen. Kunden reservieren Produkte während des Streams oder der Stories, sammeln über mehrere Tage und bezahlen später mit einem Klick im nativen Shopify-Checkout.",
    "hero.cta1": "Jetzt Demo buchen",
    "hero.cta2": "Funktionsübersicht ansehen",
    "hero.merchants": "100+ aktive Händler",
    "hero.reservationConfirmed": "Reservierung bestätigt",
    "hero.stockSecured": "Bestand gesichert ✓",
    "hero.viewers": "Zuschauer",
    "hero.imageAlt": "Händlerin beim Live-Shopping mit LiveDealz",

    // Problem Section
    "problem.badge": "Das Problem",
    "problem.headline": "Kommt dir das bekannt vor?",
    "problem.description": "Du zeigst Produkte im Livestream oder in WhatsApp-Stories. Kunden kommentieren, schreiben Nachrichten, senden Screenshots. Im Hintergrund:",
    "problem.descriptionBold": " Excel-Tabellen, WhatsApp-Chaos, manuelle Zettelwirtschaft.",
    "problem.conclusion": "Das ist nicht skalierbar. Das kostet jeden Monat",
    "problem.conclusionBold": "Umsatz und Nerven.",
    "problem.item1.title": "WhatsApp & Kommentar-Chaos",
    "problem.item1.description": "Kunden schreiben 'Ich will!', senden Screenshots, kommentieren im Stream. Du versinkst in Nachrichten.",
    "problem.item2.title": "Excel & Zettelwirtschaft",
    "problem.item2.description": "Reservierungen in Excel-Tabellen, WhatsApp-Chats und auf Zetteln. Kein System, kein Überblick.",
    "problem.item3.title": "Überverkäufe & Doppelbuchungen",
    "problem.item3.description": "Zwei Kunden reservieren das gleiche Produkt. Einer geht leer aus – und ist frustriert.",
    "problem.item4.title": "Nichtzahler blockieren Bestand",
    "problem.item4.description": "Kunden reservieren, zahlen aber nie. Dein Bestand ist blockiert, andere Käufer gehen leer aus.",
    "problem.item5.title": "Stunden für Rechnungen",
    "problem.item5.description": "Nach dem Stream: Stundenlange Nacharbeit, um alle Bestellungen manuell zusammenzuschreiben.",
    "problem.item6.title": "Nicht skalierbar",
    "problem.item6.description": "Je mehr Kunden, desto mehr Chaos. Wachstum wird zum Problem statt zur Chance.",

    // Solution Section
    "solution.badge": "Die Lösung",
    "solution.headline": "Was LiveDealz genau macht",
    "solution.description": "LiveDealz verbindet deinen Shopify-Shop mit deinen Live- und Social-Kanälen. Ein System für alles – TikTok, Instagram, WhatsApp, Discord, Telegram.",
    "solution.storefront.title": "Storefront-Modus",
    "solution.storefront.description": "Kunden gehen während des Streams oder nach Stories selbstständig in deinen Shop und sehen eine spezielle LiveDealz- oder Aktions-Collection.",
    "solution.storefront.item1": "Eigene Collection im Shopify-Shop",
    "solution.storefront.item2": "Kunden können selbst stöbern und bestellen",
    "solution.storefront.item3": "Bestand wird in Echtzeit reserviert",
    "solution.storefront.item4": "Parallel zum Stream oder asynchron nutzbar",
    "solution.dashboard.title": "Seller-Dashboard-Modus",
    "solution.dashboard.description": "Du bist live auf TikTok oder bekommst Kommentare auf WhatsApp-Stories. Kunden haben eine Kundennummer – du reservierst per Scan oder Klick.",
    "solution.dashboard.item1": "Kundennummer eingeben, Barcode scannen",
    "solution.dashboard.item2": "Reservierung wird sofort angelegt",
    "solution.dashboard.item3": "Bestand wird automatisch blockiert",
    "solution.dashboard.item4": "Ideal für interaktive Livestreams",
    "solution.atomic.title": "Atomare Bestandslogik",
    "solution.atomic.description": "Sobald reserviert wird, ist die Variante gesperrt. Keine Doppelverkäufe, kein Überbuchen.",
    "solution.collect.title": "Collect Now, Pay Later",
    "solution.collect.description": "Kunden sammeln von Montag bis Freitag, am Samstag gehen alle Checkout-Links raus.",
    "solution.shopify.title": "Nahtlose Shopify-Integration",
    "solution.shopify.description": "Nativer Checkout, Draft Orders in Shopify. Dein Shop läuft weiter wie gewohnt.",
    "solution.release.title": "Automatische Freigabe",
    "solution.release.description": "Zahlt ein Kunde nicht, wird die Reservierung nach definierter Zeit freigegeben.",
    "solution.whatsapp.title": "Perfekt für WhatsApp & Instagram Stories",
    "solution.whatsapp.description": "Nutze WhatsApp-Storys als deinen Showroom. Jeder Kontakt hat quasi eine Kundennummer. Kommentare und Anfragen wandelst du im Dashboard in Reservierungen um. Kunden können auch nach dem Stream oder den Stories weiter shoppen – alles läuft im gleichen System zusammen.",

    // Features Section
    "features.badge": "Funktionen",
    "features.headline": "Alles was du für erfolgreichen",
    "features.headlineBold": "Live-Verkauf",
    "features.headlineEnd": "brauchst",
    "features.description": "Von der Reservierung bis zur Zahlung – LiveDealz automatisiert deinen gesamten Verkaufsprozess.",
    "features.item1.title": "Echtzeit-Reservierungen",
    "features.item1.description": "Kunden reservieren Produkte live während deines Streams. Über den integrierten Shopify-Checkout wird später bezahlt.",
    "features.item2.title": "Individuelle Kundennummern",
    "features.item2.description": "Jeder Kunde erhält automatisch eine eigene Nummer. Reservierungen werden eindeutig zugeordnet – ohne Verwechslungen.",
    "features.item3.title": "Intelligente Bestandsreservierung",
    "features.item3.description": "Produkte werden bei Reservierung automatisch gesperrt. Zahlt ein Kunde nicht, wird der Bestand wieder freigegeben.",
    "features.item4.title": "Einfache Bedienung",
    "features.item4.description": "Scanne Produkte per Barcode und ordne sie der Kundennummer zu. Reservierung in Sekunden – direkt vom Smartphone.",
    "features.item5.title": "Automatische Erinnerungen",
    "features.item5.description": "Kunden werden an offene Bestellungen erinnert. Bei Bedarf werden Nichtzahler automatisch für künftige Reservierungen gesperrt.",
    "features.item6.title": "Sonderpreise im Livestream",
    "features.item6.description": "Vergib individuelle Preise während des Streams. Flexibel und ohne Einschränkungen – perfekt für Live-Aktionen.",
    "features.item7.title": "Nahtlose Integration",
    "features.item7.description": "Dein bestehender Shop läuft weiter wie gewohnt. Verkaufe gleichzeitig im Onlineshop und im Livestream – alles synchron.",
    "features.item8.title": "DSGVO-konform & sicher",
    "features.item8.description": "Deine Daten sind bei uns sicher. Server in Deutschland, höchste Sicherheitsstandards und vollständige DSGVO-Konformität.",

    // Use Cases Section
    "useCases.badge": "Anwendungsfälle",
    "useCases.headline": "Für jeden Verkaufskanal die richtige Lösung",
    "useCases.description": "Egal wie du verkaufst – LiveDealz passt sich an deinen Workflow an.",
    "useCases.case1.title": "TikTok- & Instagram-Live-Seller",
    "useCases.case1.step1": "Du präsentierst Produkte im Livestream",
    "useCases.case1.step2": "Zuschauer nennen ihre Kundennummer, du scannst Produkte",
    "useCases.case1.step3": "Parallel können andere Zuschauer im Shop kaufen",
    "useCases.case1.step4": "Keine Überverkäufe, weniger Stress, mehr Umsatz",
    "useCases.case2.title": "WhatsApp-Story-Händler",
    "useCases.case2.step1": "Produkte werden in WhatsApp-Status/Stories gezeigt",
    "useCases.case2.step2": "Kunden antworten mit 'Ich will' auf die Story",
    "useCases.case2.step3": "Du trägst das Produkt mit Kundennummer im Dashboard ein",
    "useCases.case2.step4": "Sammelaktion über mehrere Tage, am Ende gehen alle Checkout-Links raus",
    "useCases.case3.title": "Community-Sammelaktionen",
    "useCases.case3.step1": "Du hast eine Discord-, Telegram- oder WhatsApp-Gruppe",
    "useCases.case3.step2": "Aktion: 'Bis Freitag sammeln wir Bestellungen'",
    "useCases.case3.step3": "LiveDealz führt alle Reservierungen zusammen",
    "useCases.case3.step4": "Am Ende werden alle Bestellentwürfe automatisch generiert",
    "useCases.case4.title": "B2B- & Großhandels-Szenario",
    "useCases.case4.step1": "Mehrere Händler können gleichzeitig reservieren",
    "useCases.case4.step2": "Echtzeit-Bestandsanzeige – wer zuerst kommt, mahlt zuerst",
    "useCases.case4.step3": "Flexible Rechnungsstellung: erst beliefern, später abrechnen",
    "useCases.case4.step4": "Kein kompliziertes Anfragen per Mail oder Excel",

    // Origin Story Section
    "origin.badge": "Unsere Geschichte",
    "origin.headline": "Geboren aus der",
    "origin.headlineBold": "Praxis",
    "origin.description": "LiveDealz ist keine Theorie – es ist die Antwort auf echte Probleme, die wir selbst erlebt haben.",
    "origin.step": "Schritt",
    "origin.step1.title": "Der Ansturm",
    "origin.step1.description": "LSQ24, ein auf Live-Shopping spezialisierter Händler, erlebte explosives Wachstum. Doch mit dem Erfolg kamen die Probleme.",
    "origin.step2.title": "Die Überlastung",
    "origin.step2.description": "Das System brach unter der Last neuer Reservierungen zusammen. Excel-Tabellen, WhatsApp-Nachrichten und manuelle Prozesse führten zu Chaos.",
    "origin.step3.title": "Die Nichtzahler",
    "origin.step3.description": "Kunden reservierten, zahlten aber nicht. Der Bestand war blockiert, der Umsatz verloren. Der Überblick ging komplett verloren.",
    "origin.step4.title": "Die Lösung",
    "origin.step4.description": "Aus dieser Not entstand LiveDealz – entwickelt von Händlern für Händler. Eine Lösung, die alle Probleme auf einmal löst.",
    "origin.conclusion.title": "Von Händlern. Für Händler.",
    "origin.conclusion.description1": "Wir wissen genau, was du brauchst – weil wir selbst im Live-Shopping tätig waren. LiveDealz nutzt die native Reservierungsfunktion von Shopify, um Bestände für einen bestimmten Zeitraum zu sperren. Zahlt ein Kunde nicht, wird der Bestand automatisch wieder freigegeben und der Kunde für künftige Reservierungen gesperrt.",
    "origin.conclusion.description2": "Das Beste: Dein bestehender Shop läuft weiter wie gewohnt. Keine Störung von ERP-Systemen, keine komplizierten Änderungen. Verkaufe gleichzeitig über deinen Onlineshop und im Livestream – alles perfekt synchronisiert.",

    // Pricing Section
    "pricing.pioneerBadge": "Exklusives Angebot",
    "pricing.pioneerTitle": "Werde einer unserer Pionier-Kunden!",
    "pricing.pioneerDescription": "Wir sind neu am Markt und suchen engagierte Partner. Profitiere von attraktiven Einstiegspreisen!",
    "pricing.badge": "Preise",
    "pricing.headline": "Transparente Preise für jedes Business",
    "pricing.description": "Wähle den passenden Plan für dein Live-Shopping-Business. Keine versteckten Kosten.",
    "pricing.monthly": "Monatlich",
    "pricing.yearly": "Jahresvertrag",
    "pricing.savingsNote": "Sonderkonditionen für Neukunden*",
    "pricing.savingsDisclaimer": "(*) Rabattierte Preise sind 12 Monate für anfänglich bestellte Nutzer gültig.",
    "pricing.popular": "Beliebteste Wahl",
    "pricing.limitedTime": "Begrenzt",
    "pricing.startingFrom": "Ab",
    "pricing.custom": "(individuell)",
    "pricing.perMonth": "/ Monat",
    "pricing.billedYearly": "Jährlich abgerechnet:",
    "pricing.scopeTitle": "Umfang",
    "pricing.supportTitle": "Support",
    "pricing.starter.name": "Starter",
    "pricing.starter.description": "Perfekt für Anfänger und die Test-Phase",
    "pricing.starter.cta": "Jetzt starten",
    "pricing.starter.features.1": "Echtzeit-Reservierungen",
    "pricing.starter.features.2": "Individuelle Kundennummern",
    "pricing.starter.features.3": "Varianten-Filterung (Größe, Farbe)",
    "pricing.starter.features.4": "Shopify-Integration & Barcode-Scanning",
    "pricing.starter.scope.1": "Unbegrenzte Nutzer",
    "pricing.starter.scope.2": "Unbegrenzte Produkte",
    "pricing.starter.scope.3": "300 Reservierungen/Monat",
    "pricing.starter.support.1": "E-Mail-Support",
    "pricing.pro.name": "Pro",
    "pricing.pro.description": "Für semi-professionelle bis professionelle Händler",
    "pricing.pro.cta": "Jetzt upgraden",
    "pricing.pro.features.1": "Alles aus Starter +",
    "pricing.pro.features.2": "B2B-Features (Sonderpreise)",
    "pricing.pro.features.3": "Automatische Zahlungserinnerungen",
    "pricing.pro.features.4": "Nichtzahler-Sperre",
    "pricing.pro.features.5": "Live-Dashboard für Statistiken",
    "pricing.pro.scope.1": "Unbegrenzte Nutzer",
    "pricing.pro.scope.2": "Unbegrenzte Produkte",
    "pricing.pro.scope.3": "Unbegrenzte Reservierungen",
    "pricing.pro.support.1": "Priority-Support (Slack/WhatsApp)",
    "pricing.pro.support.2": "Persönliche Onboarding-Session",
    "pricing.enterprise.name": "Enterprise",
    "pricing.enterprise.description": "Für große Marken und Multi-Channel-Operator",
    "pricing.enterprise.cta": "Kontakt aufnehmen",
    "pricing.enterprise.features.1": "Alles aus Pro +",
    "pricing.enterprise.features.2": "Custom Integrations (Xentral, ERP)",
    "pricing.enterprise.features.3": "Multi-Language Support",
    "pricing.enterprise.features.4": "White-Label Option",
    "pricing.enterprise.features.5": "SLA/Uptime-Garantie",
    "pricing.enterprise.scope.1": "Unbegrenzte Nutzer",
    "pricing.enterprise.scope.2": "Unbegrenzte Produkte",
    "pricing.enterprise.scope.3": "Unbegrenzte Reservierungen",
    "pricing.enterprise.support.1": "Dedicated Account Manager",
    "pricing.enterprise.support.2": "24/7 Premium-Support",
    "pricing.enterprise.support.3": "Individuelle Schulungen",
    "pricing.testimonial": "\"LiveDealz war für uns der absolute Durchbruch! Wir haben riesige Mengen an Zeit gespart, Fehler drastisch reduziert und unseren Umsatz spürbar gesteigert. Es fühlt sich an, als hätten wir unser Business komplett neu erfunden!\"",
    "pricing.testimonialAuthor": "Ali Kaawar",
    "pricing.testimonialRole": "Geschäftsführer @ LSQ24",

    // FAQ Section
    "faq.headline": "Häufig gestellte Fragen",
    "faq.q1": "Was ist LiveDealz und wie funktioniert es?",
    "faq.a1": "LiveDealz ist eine Plattform, die es dir ermöglicht, Produkte in Echtzeit während deines Livestreams zu verkaufen. Kunden können Artikel reservieren, ohne den Stream zu verlassen oder sofort zu bezahlen. Die Reservierungen werden automatisch verwaltet und können zu einem späteren Zeitpunkt gesammelt bezahlt werden.",
    "faq.q2": "Wie hilft mir LiveDealz, meine Verkäufe zu verwalten?",
    "faq.a2": "LiveDealz bietet eine zentrale Übersicht aller Reservierungen und Bestellungen. Du kannst Bestände in Echtzeit verfolgen, Kundenanfragen verwalten und Zahlungen automatisch abwickeln lassen. Unsere KI filtert Spam-Reservierungen und optimiert deinen Lagerbestand.",
    "faq.q3": "Kann ich LiveDealz verwenden, wenn ich nicht live bin?",
    "faq.a3": "Ja! Kunden können auch nach dem Livestream weiter reservieren und einkaufen. Deine Produkte bleiben verfügbar und der Verkaufsprozess läuft automatisiert weiter – so maximierst du deinen Umsatz rund um die Uhr.",
    "faq.q4": "Wie werden Bestellungen in Shopify integriert?",
    "faq.a4": "LiveDealz lässt sich nahtlos in deinen Shopify-Store integrieren. Alle Reservierungen und Bestellungen werden automatisch synchronisiert, sodass du eine einheitliche Übersicht behältst und keine manuelle Dateneingabe nötig ist.",
    "faq.q5": "Wie sicher sind meine Daten bei LiveDealz?",
    "faq.a5": "Deine Daten sind bei uns bestens geschützt. Unsere Server stehen in Deutschland und sind DSGVO-konform. Wir verwenden moderne Verschlüsselungstechnologien und führen regelmäßige Sicherheitsaudits durch.",

    // Tech Trust Section
    "tech.headline": "Technologie, der du vertrauen kannst",
    "tech.description": "Moderne Infrastruktur für zuverlässige Performance – auch bei hoher Last.",
    "tech.item1.title": "Event-getriebene Architektur",
    "tech.item1.description": "Webhooks von Shopify werden in Echtzeit verarbeitet. Jede Bestandsänderung wird sofort synchronisiert.",
    "tech.item2.title": "Skalierbare Queue-Verarbeitung",
    "tech.item2.description": "Verarbeitung über Queues ermöglicht hohe Last bei niedrigen Fixkosten für Händler.",
    "tech.item3.title": "Privacy by Design",
    "tech.item3.description": "Speicherung nur minimaler IDs. Keine personenbezogenen Daten in unserem System.",
    "tech.item4.title": "Server in der EU",
    "tech.item4.description": "DSGVO-konform. Alle Daten werden auf Servern in der Europäischen Union verarbeitet.",

    // CTA Section
    "cta.headline": "Maximiere deinen Erfolg im Live-Shopping",
    "cta.description": "Mit LiveDealz bringst du dein Geschäft auf das nächste Level. Steigere deinen Umsatz durch Echtzeit-Reservierungen, automatisiere deine Abläufe und schaffe ein nahtloses Einkaufserlebnis für deine Kunden.",
    "cta.button1": "Jetzt Probemonat sichern",
    "cta.button2": "Kontakt aufnehmen",

    // Contact Section
    "contact.badge": "Kontakt",
    "contact.headline": "Bereit durchzustarten?",
    "contact.description": "Lass uns gemeinsam besprechen, wie LiveDealz dein Live-Shopping-Business auf das nächste Level bringt. Buche eine unverbindliche Demo oder schreib uns direkt.",
    "contact.emailLabel": "E-Mail",
    "contact.responseLabel": "Antwortzeit",
    "contact.responseTime": "Innerhalb von 24 Stunden",

    // Footer
    "footer.tagline": "Die Plattform für Live-, Story- und Sammelverkäufe ohne Chaos.",
    "footer.description": "Reservieren. Sammeln. Bezahlen. Ein System, ein Bestand – für TikTok, Instagram, WhatsApp und Community-Verkäufe.",
    "footer.product": "Produkt",
    "footer.features": "Funktionen",
    "footer.useCases": "Anwendungsfälle",
    "footer.pricing": "Preise",
    "footer.faq": "FAQ",
    "footer.resources": "Ressourcen",
    "footer.bookDemo": "Demo buchen",
    "footer.contact": "Kontakt",
    "footer.legal": "Rechtliches",
    "footer.imprint": "Impressum",
    "footer.privacy": "Datenschutz",
    "footer.terms": "AGB",
    "footer.copyright": "Alle Rechte vorbehalten.",
    "footer.businessOnly": "Hinweis: Die Angebote und Inhalte auf dieser Webseite richten sich ausschließlich an Unternehmer und gewerbliche Kunden.",

    // B2B Page
    "b2b.badge": "LiveDealz für B2B",
    "b2b.painPoint": "Schluss mit Überverkaufs-Risiko und manueller Bestell-Bremse.",
    "b2b.painPointHighlight": "Geld liebt Speed.",
    "b2b.headline": "Endlich Großhandel ohne Risiko:",
    "b2b.headlineHighlight": "Gesicherte Ware durch Echtzeit-Reservierung",
    "b2b.subheadline": "Garantierte Bestandsreservierung im Moment der Bestellung. Keine Überverkäufe, keine Rückfragen, keine verlorenen Aufträge.",
    "b2b.cta": "Demo buchen: Warensicherheit in Echtzeit erleben",
    "b2b.problemTitle": "Das Risiko kennen Sie",
    "b2b.problemDescription": "Ihre Händler bestellen per E-Mail oder Excel. Ständige Rückfragen zu Verfügbarkeiten, manuelle Bestandsprüfungen und chaotische Kommunikation kosten Zeit und Geld.",
    "b2b.problemConclusion": "Und das Schlimmste: Wenn mehrere Händler gleichzeitig zuschlagen, verkaufen Sie über – und müssen stornieren. Verlorenes Vertrauen, verlorener Umsatz.",
    "b2b.solutionBadge": "Die Lösung",
    "b2b.solutionTitle": "Garantierte Warensicherheit mit",
    "b2b.solutionDescription": "Atomare Reservierungen im Moment der Bestellung. Ihre Händler sehen nur, was verfügbar ist – und bekommen garantiert, was sie bestellen.",
    "b2b.benefit1.title": "Atomare Reservierungsgarantie",
    "b2b.benefit1.description": "Ihre Ware wird im Moment der Bestellung verbindlich aus dem Bestand ausgebucht. Kein Überverkauf mehr. Händler sehen nur, was sie garantiert bekommen.",
    "b2b.benefit2.title": "Echtzeit-Verfügbarkeit",
    "b2b.benefit2.description": "Bestand wird im Moment der Bestellung verbindlich reserviert. Sofort sichtbar, was verfügbar ist – keine Rückfragen mehr nötig.",
    "b2b.benefit3.title": "Marktplatz-Erlebnis",
    "b2b.benefit3.description": "Präsentieren Sie Ihr Sortiment wie auf einem digitalen Markt. Händler wählen selbst aus, was und wie viel sie kaufen wollen – wer zuerst kommt, mahlt zuerst.",
    "b2b.benefit4.title": "Flexible Rechnungsstellung",
    "b2b.benefit4.description": "Beliefern Sie erst, stellen Sie die Rechnung später. LiveDealz sammelt alle Bestellungen und Sie entscheiden, wann abgerechnet wird.",
    "b2b.benefit5.title": "Zukunftssichere B2B-Plattform",
    "b2b.benefit5.description": "Wir nutzen Shopify als Backbone, da es die größte Schnittstellenabdeckung zu allen ERP-Systemen bietet. Nutzen Sie die bewährte und mobile Technologie für Ihren Großhandel.",
    "b2b.benefit6.title": "Volle Flexibilität",
    "b2b.benefit6.description": "Bestellungen können jederzeit und von überall aufgegeben werden. Durch die Shopify-Basis erhalten Ihre Händler ein natives, mobiles Kauferlebnis – ob am PC, Tablet oder Handy.",
    "b2b.speedTitle": "Der Speed-Gewinn zählt",
    "b2b.speedDescription": "Ja, Shopify kostet ca. 30–40 €/Monat. Aber wie viel Geld verlieren Sie pro Monat durch manuelles Chaos, ineffiziente Rückfragen und stornierte Überverkäufe?",
    "b2b.speedConclusion": "LiveDealz nutzt Shopify, um Ihnen den Speed und die Sicherheit zu geben, die Ihr Großhandel braucht.",
    "b2b.useCasesBadge": "Anwendungsfälle",
    "b2b.useCasesTitle": "Perfekt für Ihren",
    "b2b.useCasesTitleHighlight": "B2B-Vertrieb",
    "b2b.useCasesDescription": "Egal ob Großhandel, Hersteller oder Importeur – LiveDealz passt sich Ihrem Geschäftsmodell an und macht B2B-Bestellungen sicher und effizient.",
    "b2b.useCase1": "Großhändler mit regelmäßigen Orderrunden",
    "b2b.useCase2": "Hersteller mit Direktvertrieb an Händler",
    "b2b.useCase3": "Showroom-Verkäufe mit Live-Präsentation",
    "b2b.useCase4": "Saisonale Kollektionsvorstellungen",
    "b2b.useCase5": "B2B-Marktplätze und Messen",
    "b2b.howItWorksTitle": "So funktioniert's",
    "b2b.step1.title": "Produkte präsentieren",
    "b2b.step1.description": "Zeigen Sie Ihr Sortiment live oder auf einer permanenten Bestellseite.",
    "b2b.step2.title": "Händler bestellen selbst",
    "b2b.step2.description": "Ihre Händler wählen Produkte und Mengen – in Echtzeit und selbstständig.",
    "b2b.step3.title": "Bestand wird garantiert reserviert",
    "b2b.step3.description": "Im Moment der Bestellung wird die Ware verbindlich ausgebucht – keine Doppelverkäufe möglich.",
    "b2b.step4.title": "Rechnung nach Lieferung",
    "b2b.step4.description": "Sie entscheiden, wann die Bestellung abgerechnet wird.",
    "b2b.ctaTitle": "Bereit für risikofreien B2B-Vertrieb?",
    "b2b.ctaDescription": "Erleben Sie, wie LiveDealz Überverkäufe eliminiert und Ihren Großhandel mit garantierter Echtzeit-Reservierung revolutioniert.",

    // Draft Orders Feature Page
    "draftOrders.seo.title": "Draft Orders – Das Herzstück von LiveDealz | Shopify Reservierungslogik",
    "draftOrders.seo.description": "Erfahre, wie LiveDealz Shopify Draft Orders nutzt, um atomare Reservierungen zu ermöglichen. Kein Überverkauf, automatische Bestandsfreigabe.",
    "draftOrders.badge": "Kernfunktion",
    "draftOrders.headline": "Draft Orders:",
    "draftOrders.headlineBold": "Die Magie hinter LiveDealz",
    "draftOrders.description": "Shopify Draft Orders sind das Herzstück unserer Reservierungslogik. Sie ermöglichen atomare Bestandssicherung – ohne komplizierte Workarounds.",
    "draftOrders.whatBadge": "Was sind Draft Orders?",
    "draftOrders.whatTitle": "Shopifys native Reservierungsfunktion",
    "draftOrders.whatDescription": "Draft Orders sind Bestellentwürfe in Shopify, die Bestand reservieren, bevor der Kunde bezahlt. LiveDealz nutzt diese native Funktion für sichere Live-Verkäufe.",
    "draftOrders.what1.title": "Bestellentwurf",
    "draftOrders.what1.description": "Ein Draft Order ist wie eine Bestellung, die noch nicht abgeschlossen ist – aber der Bestand ist bereits reserviert.",
    "draftOrders.what2.title": "Bestand gesperrt",
    "draftOrders.what2.description": "Sobald ein Draft Order erstellt wird, ist die Variante für andere Käufer nicht mehr verfügbar.",
    "draftOrders.what3.title": "Automatische Freigabe",
    "draftOrders.what3.description": "Zahlt der Kunde nicht innerhalb der Frist, wird der Bestand automatisch wieder freigegeben.",
    "draftOrders.howBadge": "So funktioniert's",
    "draftOrders.howTitle": "Der LiveDealz Draft Order Workflow",
    "draftOrders.howDescription": "In 5 Schritten von der Reservierung zur Bestellung – vollautomatisch und ohne Risiko.",
    "draftOrders.step1.title": "Kunde reserviert",
    "draftOrders.step1.description": "Während deines Livestreams oder über Stories reserviert der Kunde ein Produkt mit seiner Kundennummer.",
    "draftOrders.step2.title": "Draft Order wird erstellt",
    "draftOrders.step2.description": "LiveDealz erstellt automatisch einen Shopify Draft Order. Der Bestand wird sofort reserviert.",
    "draftOrders.step3.title": "Bestand ist gesichert",
    "draftOrders.step3.description": "Die Variante ist für andere Käufer nicht mehr verfügbar. Keine Doppelverkäufe möglich.",
    "draftOrders.step4.title": "Checkout-Link wird versendet",
    "draftOrders.step4.description": "Der Kunde erhält einen Link zur Bezahlung. Du entscheidest, wann dieser versendet wird.",
    "draftOrders.step5.title": "Zahlung oder Freigabe",
    "draftOrders.step5.description": "Zahlt der Kunde, wird die Bestellung abgeschlossen. Zahlt er nicht, wird der Bestand automatisch freigegeben.",
    "draftOrders.benefitsBadge": "Vorteile",
    "draftOrders.benefitsTitle": "Warum Draft Orders der Game-Changer sind",
    "draftOrders.benefit1.title": "Keine Überverkäufe",
    "draftOrders.benefit1.description": "Bestand wird atomar reserviert. Zwei Kunden können niemals das gleiche Produkt reservieren.",
    "draftOrders.benefit2.title": "Automatische Freigabe",
    "draftOrders.benefit2.description": "Nichtzahler blockieren deinen Bestand nicht mehr. Nach Ablauf der Frist wird automatisch freigegeben.",
    "draftOrders.benefit3.title": "Sofortige Reservierung",
    "draftOrders.benefit3.description": "Die Reservierung erfolgt in Millisekunden. Deine Kunden sehen sofort, ob ein Produkt verfügbar ist.",
    "draftOrders.benefit4.title": "Collect Now, Pay Later",
    "draftOrders.benefit4.description": "Kunden können über mehrere Tage sammeln und am Ende alles auf einmal bezahlen.",
    "draftOrders.benefit5.title": "Native Shopify-Funktion",
    "draftOrders.benefit5.description": "Keine Drittanbieter, keine komplizierten Workarounds. Draft Orders sind Teil von Shopify.",
    "draftOrders.benefit6.title": "ERP-kompatibel",
    "draftOrders.benefit6.description": "Dein bestehendes System läuft weiter. Draft Orders integrieren sich nahtlos in deinen Workflow.",
    "draftOrders.compareTitle": "Der Unterschied macht's",
    "draftOrders.compareDescription": "Vergleiche manuelle Prozesse mit der Draft Order Logik von LiveDealz.",
    "draftOrders.compareBefore": "Manuell",
    "draftOrders.compareAfter": "Mit LiveDealz",
    "draftOrders.compare.feature1": "Bestandsreservierung",
    "draftOrders.compare.before1": "Excel-Tabelle",
    "draftOrders.compare.after1": "Automatisch",
    "draftOrders.compare.feature2": "Überverkaufsschutz",
    "draftOrders.compare.before2": "Nicht vorhanden",
    "draftOrders.compare.after2": "100% garantiert",
    "draftOrders.compare.feature3": "Atomare Reservierung",
    "draftOrders.compare.feature4": "Nichtzahler-Handling",
    "draftOrders.compare.before4": "Manuell prüfen",
    "draftOrders.compare.after4": "Auto-Freigabe",
    "draftOrders.compare.feature5": "ERP-Integration",
    "draftOrders.relatedTitle": "Mehr erfahren",
    "draftOrders.related1.title": "Shopify Integration",
    "draftOrders.related1.description": "Erfahre, wie LiveDealz nahtlos mit deinem Shop zusammenarbeitet.",
    "draftOrders.related2.title": "LiveDealz vs. Manuell",
    "draftOrders.related2.description": "Detaillierter Vergleich: Was sparst du wirklich?",
    "draftOrders.related3.title": "TikTok & Instagram Live",
    "draftOrders.related3.description": "So nutzt du Draft Orders in deinen Livestreams.",
    "draftOrders.ctaTitle": "Bereit für sichere Live-Verkäufe?",
    "draftOrders.ctaDescription": "Erlebe, wie Draft Orders dein Live-Shopping revolutionieren – ohne Überverkäufe, ohne Stress.",
  },
  en: {
    // Promo Banner
    "promo.starterOffer": "🎉 Starter plan for only €79/month – Offer valid until 31.12.2025!",

    // Navbar
    "nav.features": "Features",
    "nav.draftOrders": "Draft Orders",
    "nav.benefits": "Benefits",
    "nav.pricing": "Pricing",
    "nav.b2b": "B2B",
    "nav.faq": "FAQ",
    "nav.contact": "Contact",
    "nav.bookDemo": "Book Demo",

    // Hero
    "hero.badge": "Community Commerce Engine",
    "hero.headline1": "Reserve.",
    "hero.headline2": "Collect.",
    "hero.headline3": "Pay.",
    "hero.subheadline": "Maximum Sales. Minimum Effort.",
    "hero.description1": "Whether live stream, WhatsApp story or collection campaign –",
    "hero.description1Bold": " one system, one inventory, no chaos.",
    "hero.description2": "LiveDealz connects live shopping, stories, and collection campaigns. Customers reserve products during your stream or stories, collect over several days, and pay later with one click in the native Shopify checkout.",
    "hero.cta1": "Book Demo Now",
    "hero.cta2": "View Features Overview",
    "hero.merchants": "100+ active merchants",
    "hero.reservationConfirmed": "Reservation confirmed",
    "hero.stockSecured": "Stock secured ✓",
    "hero.viewers": "viewers",
    "hero.imageAlt": "Merchant during live shopping with LiveDealz",

    // Problem Section
    "problem.badge": "The Problem",
    "problem.headline": "Does this sound familiar?",
    "problem.description": "You show products in livestreams or WhatsApp stories. Customers comment, send messages, share screenshots. In the background:",
    "problem.descriptionBold": " Excel spreadsheets, WhatsApp chaos, manual paperwork.",
    "problem.conclusion": "This doesn't scale. Every month it costs you",
    "problem.conclusionBold": "revenue and nerves.",
    "problem.item1.title": "WhatsApp & Comment Chaos",
    "problem.item1.description": "Customers write 'I want it!', send screenshots, comment during streams. You're drowning in messages.",
    "problem.item2.title": "Excel & Paper Chaos",
    "problem.item2.description": "Reservations in Excel spreadsheets, WhatsApp chats, and on paper notes. No system, no overview.",
    "problem.item3.title": "Overselling & Double Bookings",
    "problem.item3.description": "Two customers reserve the same product. One goes empty-handed – and is frustrated.",
    "problem.item4.title": "Non-payers Block Inventory",
    "problem.item4.description": "Customers reserve but never pay. Your inventory is blocked, other buyers miss out.",
    "problem.item5.title": "Hours on Invoices",
    "problem.item5.description": "After the stream: hours of work to manually compile all orders.",
    "problem.item6.title": "Not Scalable",
    "problem.item6.description": "More customers means more chaos. Growth becomes a problem instead of an opportunity.",

    // Solution Section
    "solution.badge": "The Solution",
    "solution.headline": "What LiveDealz Does",
    "solution.description": "LiveDealz connects your Shopify store with your live and social channels. One system for everything – TikTok, Instagram, WhatsApp, Discord, Telegram.",
    "solution.storefront.title": "Storefront Mode",
    "solution.storefront.description": "Customers browse your shop independently during or after streams and see a special LiveDealz or campaign collection.",
    "solution.storefront.item1": "Dedicated collection in Shopify store",
    "solution.storefront.item2": "Customers can browse and order independently",
    "solution.storefront.item3": "Inventory reserved in real-time",
    "solution.storefront.item4": "Usable in parallel with stream or asynchronously",
    "solution.dashboard.title": "Seller Dashboard Mode",
    "solution.dashboard.description": "You're live on TikTok or receiving WhatsApp story comments. Customers have a customer number – you reserve with a scan or click.",
    "solution.dashboard.item1": "Enter customer number, scan barcode",
    "solution.dashboard.item2": "Reservation created instantly",
    "solution.dashboard.item3": "Inventory automatically blocked",
    "solution.dashboard.item4": "Ideal for interactive livestreams",
    "solution.atomic.title": "Atomic Inventory Logic",
    "solution.atomic.description": "Once reserved, the variant is locked. No double sales, no overbooking.",
    "solution.collect.title": "Collect Now, Pay Later",
    "solution.collect.description": "Customers collect Monday to Friday, checkout links go out on Saturday.",
    "solution.shopify.title": "Seamless Shopify Integration",
    "solution.shopify.description": "Native checkout, draft orders in Shopify. Your shop continues as usual.",
    "solution.release.title": "Automatic Release",
    "solution.release.description": "If a customer doesn't pay, the reservation is released after a defined time.",
    "solution.whatsapp.title": "Perfect for WhatsApp & Instagram Stories",
    "solution.whatsapp.description": "Use WhatsApp stories as your showroom. Each contact has a customer number. Convert comments and inquiries into reservations via the dashboard. Customers can continue shopping after the stream or stories – everything runs in the same system.",

    // Features Section
    "features.badge": "Features",
    "features.headline": "Everything you need for successful",
    "features.headlineBold": "live selling",
    "features.headlineEnd": "",
    "features.description": "From reservation to payment – LiveDealz automates your entire sales process.",
    "features.item1.title": "Real-time Reservations",
    "features.item1.description": "Customers reserve products live during your stream. Payment is made later through the integrated Shopify checkout.",
    "features.item2.title": "Individual Customer Numbers",
    "features.item2.description": "Each customer automatically receives their own number. Reservations are clearly assigned – no mix-ups.",
    "features.item3.title": "Smart Inventory Reservation",
    "features.item3.description": "Products are automatically locked when reserved. If a customer doesn't pay, inventory is released.",
    "features.item4.title": "Easy Operation",
    "features.item4.description": "Scan products via barcode and assign them to customer numbers. Reservation in seconds – directly from your smartphone.",
    "features.item5.title": "Automatic Reminders",
    "features.item5.description": "Customers are reminded about open orders. Non-payers can be automatically blocked for future reservations.",
    "features.item6.title": "Special Livestream Prices",
    "features.item6.description": "Assign individual prices during the stream. Flexible and without restrictions – perfect for live deals.",
    "features.item7.title": "Seamless Integration",
    "features.item7.description": "Your existing shop continues as usual. Sell simultaneously in your online shop and livestream – all synchronized.",
    "features.item8.title": "GDPR Compliant & Secure",
    "features.item8.description": "Your data is safe with us. Servers in Germany, highest security standards, and full GDPR compliance.",

    // Use Cases Section
    "useCases.badge": "Use Cases",
    "useCases.headline": "The Right Solution for Every Sales Channel",
    "useCases.description": "No matter how you sell – LiveDealz adapts to your workflow.",
    "useCases.case1.title": "TikTok & Instagram Live Sellers",
    "useCases.case1.step1": "You present products in the livestream",
    "useCases.case1.step2": "Viewers give their customer number, you scan products",
    "useCases.case1.step3": "Others can shop in parallel in your store",
    "useCases.case1.step4": "No overselling, less stress, more revenue",
    "useCases.case2.title": "WhatsApp Story Merchants",
    "useCases.case2.step1": "Products are shown in WhatsApp status/stories",
    "useCases.case2.step2": "Customers reply with 'I want it' to the story",
    "useCases.case2.step3": "You enter the product with customer number in the dashboard",
    "useCases.case2.step4": "Collection over several days, all checkout links sent at the end",
    "useCases.case3.title": "Community Collection Campaigns",
    "useCases.case3.step1": "You have a Discord, Telegram, or WhatsApp group",
    "useCases.case3.step2": "Campaign: 'We collect orders until Friday'",
    "useCases.case3.step3": "LiveDealz consolidates all reservations",
    "useCases.case3.step4": "All draft orders are automatically generated at the end",
    "useCases.case4.title": "B2B & Wholesale Scenario",
    "useCases.case4.step1": "Multiple dealers can reserve simultaneously",
    "useCases.case4.step2": "Real-time inventory display – first come, first served",
    "useCases.case4.step3": "Flexible invoicing: deliver first, invoice later",
    "useCases.case4.step4": "No complicated requests via email or Excel",

    // Origin Story Section
    "origin.badge": "Our Story",
    "origin.headline": "Born from",
    "origin.headlineBold": "Practice",
    "origin.description": "LiveDealz isn't theory – it's the answer to real problems we experienced ourselves.",
    "origin.step": "Step",
    "origin.step1.title": "The Rush",
    "origin.step1.description": "LSQ24, a merchant specialized in live shopping, experienced explosive growth. But with success came problems.",
    "origin.step2.title": "The Overload",
    "origin.step2.description": "The system collapsed under the weight of new reservations. Excel spreadsheets, WhatsApp messages, and manual processes led to chaos.",
    "origin.step3.title": "The Non-payers",
    "origin.step3.description": "Customers reserved but didn't pay. Inventory was blocked, revenue lost. Overview was completely gone.",
    "origin.step4.title": "The Solution",
    "origin.step4.description": "From this necessity, LiveDealz was born – developed by merchants for merchants. A solution that solves all problems at once.",
    "origin.conclusion.title": "By Merchants. For Merchants.",
    "origin.conclusion.description1": "We know exactly what you need – because we were in live shopping ourselves. LiveDealz uses Shopify's native reservation feature to lock inventory for a defined period. If a customer doesn't pay, inventory is automatically released and the customer is blocked for future reservations.",
    "origin.conclusion.description2": "The best part: Your existing shop continues as usual. No disruption to ERP systems, no complicated changes. Sell simultaneously via your online shop and livestream – all perfectly synchronized.",

    // Pricing Section
    "pricing.pioneerBadge": "Exclusive Offer",
    "pricing.pioneerTitle": "Become One of Our Pioneer Customers!",
    "pricing.pioneerDescription": "We're new to the market and looking for dedicated partners. Benefit from attractive entry prices!",
    "pricing.badge": "Pricing",
    "pricing.headline": "Transparent Pricing for Every Business",
    "pricing.description": "Choose the right plan for your live shopping business. No hidden costs.",
    "pricing.monthly": "Monthly",
    "pricing.yearly": "Annual",
    "pricing.savingsNote": "Special conditions for new customers*",
    "pricing.savingsDisclaimer": "(*) Discounted prices are valid for 12 months for initially ordered users.",
    "pricing.popular": "Most Popular",
    "pricing.limitedTime": "Limited",
    "pricing.startingFrom": "From",
    "pricing.custom": "(custom)",
    "pricing.perMonth": "/ month",
    "pricing.billedYearly": "Billed annually:",
    "pricing.scopeTitle": "Scope",
    "pricing.supportTitle": "Support",
    "pricing.starter.name": "Starter",
    "pricing.starter.description": "Perfect for beginners and testing phase",
    "pricing.starter.cta": "Get Started",
    "pricing.starter.features.1": "Real-time reservations",
    "pricing.starter.features.2": "Individual customer numbers",
    "pricing.starter.features.3": "Variant filtering (size, color)",
    "pricing.starter.features.4": "Shopify integration & barcode scanning",
    "pricing.starter.scope.1": "Unlimited users",
    "pricing.starter.scope.2": "Unlimited products",
    "pricing.starter.scope.3": "300 reservations/month",
    "pricing.starter.support.1": "Email support",
    "pricing.pro.name": "Pro",
    "pricing.pro.description": "For semi-professional to professional merchants",
    "pricing.pro.cta": "Upgrade Now",
    "pricing.pro.features.1": "Everything in Starter +",
    "pricing.pro.features.2": "B2B features (special prices)",
    "pricing.pro.features.3": "Automatic payment reminders",
    "pricing.pro.features.4": "Non-payer blocking",
    "pricing.pro.features.5": "Live dashboard for statistics",
    "pricing.pro.scope.1": "Unlimited users",
    "pricing.pro.scope.2": "Unlimited products",
    "pricing.pro.scope.3": "Unlimited reservations",
    "pricing.pro.support.1": "Priority support (Slack/WhatsApp)",
    "pricing.pro.support.2": "Personal onboarding session",
    "pricing.enterprise.name": "Enterprise",
    "pricing.enterprise.description": "For large brands and multi-channel operators",
    "pricing.enterprise.cta": "Contact Us",
    "pricing.enterprise.features.1": "Everything in Pro +",
    "pricing.enterprise.features.2": "Custom integrations (Xentral, ERP)",
    "pricing.enterprise.features.3": "Multi-language support",
    "pricing.enterprise.features.4": "White-label option",
    "pricing.enterprise.features.5": "SLA/Uptime guarantee",
    "pricing.enterprise.scope.1": "Unlimited users",
    "pricing.enterprise.scope.2": "Unlimited products",
    "pricing.enterprise.scope.3": "Unlimited reservations",
    "pricing.enterprise.support.1": "Dedicated account manager",
    "pricing.enterprise.support.2": "24/7 premium support",
    "pricing.enterprise.support.3": "Individual training",
    "pricing.testimonial": "\"LiveDealz was a complete breakthrough for us! We saved huge amounts of time, drastically reduced errors, and noticeably increased our revenue. It feels like we've completely reinvented our business!\"",
    "pricing.testimonialAuthor": "Ali Kaawar",
    "pricing.testimonialRole": "CEO @ LSQ24",

    // FAQ Section
    "faq.headline": "Frequently Asked Questions",
    "faq.q1": "What is LiveDealz and how does it work?",
    "faq.a1": "LiveDealz is a platform that allows you to sell products in real-time during your livestream. Customers can reserve items without leaving the stream or paying immediately. Reservations are automatically managed and can be paid for collectively at a later time.",
    "faq.q2": "How does LiveDealz help me manage my sales?",
    "faq.a2": "LiveDealz provides a central overview of all reservations and orders. You can track inventory in real-time, manage customer inquiries, and have payments processed automatically. Our AI filters spam reservations and optimizes your inventory.",
    "faq.q3": "Can I use LiveDealz when I'm not live?",
    "faq.a3": "Yes! Customers can continue to reserve and shop after the livestream. Your products remain available and the sales process continues automatically – maximizing your revenue around the clock.",
    "faq.q4": "How are orders integrated into Shopify?",
    "faq.a4": "LiveDealz integrates seamlessly into your Shopify store. All reservations and orders are automatically synchronized, so you maintain a unified overview and no manual data entry is needed.",
    "faq.q5": "How secure is my data with LiveDealz?",
    "faq.a5": "Your data is well protected with us. Our servers are located in Germany and are GDPR compliant. We use modern encryption technologies and conduct regular security audits.",

    // Tech Trust Section
    "tech.headline": "Technology You Can Trust",
    "tech.description": "Modern infrastructure for reliable performance – even under high load.",
    "tech.item1.title": "Event-driven Architecture",
    "tech.item1.description": "Webhooks from Shopify are processed in real-time. Every inventory change is synchronized immediately.",
    "tech.item2.title": "Scalable Queue Processing",
    "tech.item2.description": "Processing via queues enables high load at low fixed costs for merchants.",
    "tech.item3.title": "Privacy by Design",
    "tech.item3.description": "Only minimal IDs are stored. No personal data in our system.",
    "tech.item4.title": "Servers in the EU",
    "tech.item4.description": "GDPR compliant. All data is processed on servers in the European Union.",

    // CTA Section
    "cta.headline": "Maximize Your Live Shopping Success",
    "cta.description": "With LiveDealz, take your business to the next level. Increase your revenue through real-time reservations, automate your processes, and create a seamless shopping experience for your customers.",
    "cta.button1": "Get Your Trial Month",
    "cta.button2": "Contact Us",

    // Contact Section
    "contact.badge": "Contact",
    "contact.headline": "Ready to Get Started?",
    "contact.description": "Let's discuss how LiveDealz can take your live shopping business to the next level. Book a free demo or contact us directly.",
    "contact.emailLabel": "Email",
    "contact.responseLabel": "Response Time",
    "contact.responseTime": "Within 24 hours",

    // Footer
    "footer.tagline": "The platform for live, story, and collection sales without chaos.",
    "footer.description": "Reserve. Collect. Pay. One system, one inventory – for TikTok, Instagram, WhatsApp, and community sales.",
    "footer.product": "Product",
    "footer.features": "Features",
    "footer.useCases": "Use Cases",
    "footer.pricing": "Pricing",
    "footer.faq": "FAQ",
    "footer.resources": "Resources",
    "footer.bookDemo": "Book Demo",
    "footer.contact": "Contact",
    "footer.legal": "Legal",
    "footer.imprint": "Imprint",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms",
    "footer.copyright": "All rights reserved.",
    "footer.businessOnly": "Note: The offers and content on this website are intended exclusively for businesses and commercial customers.",

    // B2B Page
    "b2b.badge": "LiveDealz for B2B",
    "b2b.painPoint": "End overselling risk and manual order bottlenecks.",
    "b2b.painPointHighlight": "Money loves speed.",
    "b2b.headline": "Finally wholesale without risk:",
    "b2b.headlineHighlight": "Secured inventory through real-time reservation",
    "b2b.subheadline": "Guaranteed inventory reservation at the moment of order. No overselling, no inquiries, no lost orders.",
    "b2b.cta": "Book demo: Experience inventory security in real-time",
    "b2b.problemTitle": "You Know This Risk",
    "b2b.problemDescription": "Your dealers order via email or Excel. Constant inquiries about availability, manual inventory checks, and chaotic communication cost time and money.",
    "b2b.problemConclusion": "And the worst part: When multiple dealers order simultaneously, you oversell – and have to cancel. Lost trust, lost revenue.",
    "b2b.solutionBadge": "The Solution",
    "b2b.solutionTitle": "Guaranteed inventory security with",
    "b2b.solutionDescription": "Atomic reservations at the moment of order. Your dealers see only what's available – and are guaranteed to get what they order.",
    "b2b.benefit1.title": "Atomic Reservation Guarantee",
    "b2b.benefit1.description": "Your goods are permanently booked out of inventory at the moment of order. No more overselling. Dealers see only what they're guaranteed to receive.",
    "b2b.benefit2.title": "Real-time Availability",
    "b2b.benefit2.description": "Inventory is permanently reserved at the moment of order. Instantly visible what's available – no more inquiries needed.",
    "b2b.benefit3.title": "Marketplace Experience",
    "b2b.benefit3.description": "Present your assortment like a digital marketplace. Dealers choose what and how much they want to buy – first come, first served.",
    "b2b.benefit4.title": "Flexible Invoicing",
    "b2b.benefit4.description": "Deliver first, invoice later. LiveDealz collects all orders and you decide when to bill.",
    "b2b.benefit5.title": "Future-proof B2B Platform",
    "b2b.benefit5.description": "We use Shopify as backbone because it offers the largest interface coverage to all ERP systems. Use proven and mobile technology for your wholesale.",
    "b2b.benefit6.title": "Full Flexibility",
    "b2b.benefit6.description": "Orders can be placed anytime, anywhere. With Shopify as the base, your dealers get a native, mobile buying experience – on PC, tablet, or phone.",
    "b2b.speedTitle": "The Speed Advantage Counts",
    "b2b.speedDescription": "Yes, Shopify costs about €30-40/month. But how much money do you lose per month through manual chaos, inefficient inquiries, and cancelled oversales?",
    "b2b.speedConclusion": "LiveDealz uses Shopify to give you the speed and security your wholesale needs.",
    "b2b.useCasesBadge": "Use Cases",
    "b2b.useCasesTitle": "Perfect for Your",
    "b2b.useCasesTitleHighlight": "B2B Distribution",
    "b2b.useCasesDescription": "Whether wholesaler, manufacturer, or importer – LiveDealz adapts to your business model and makes B2B orders secure and efficient.",
    "b2b.useCase1": "Wholesalers with regular order rounds",
    "b2b.useCase2": "Manufacturers with direct sales to dealers",
    "b2b.useCase3": "Showroom sales with live presentation",
    "b2b.useCase4": "Seasonal collection presentations",
    "b2b.useCase5": "B2B marketplaces and trade shows",
    "b2b.howItWorksTitle": "How It Works",
    "b2b.step1.title": "Present products",
    "b2b.step1.description": "Show your assortment live or on a permanent order page.",
    "b2b.step2.title": "Dealers order themselves",
    "b2b.step2.description": "Your dealers choose products and quantities – in real-time and independently.",
    "b2b.step3.title": "Inventory is guaranteed reserved",
    "b2b.step3.description": "At the moment of order, the goods are permanently booked out – no double sales possible.",
    "b2b.step4.title": "Invoice after delivery",
    "b2b.step4.description": "You decide when the order is billed.",
    "b2b.ctaTitle": "Ready for risk-free B2B distribution?",
    "b2b.ctaDescription": "Experience how LiveDealz eliminates overselling and revolutionizes your wholesale with guaranteed real-time reservation.",

    // Draft Orders Feature Page
    "draftOrders.seo.title": "Draft Orders – The Heart of LiveDealz | Shopify Reservation Logic",
    "draftOrders.seo.description": "Learn how LiveDealz uses Shopify Draft Orders to enable atomic reservations. No overselling, automatic inventory release.",
    "draftOrders.badge": "Core Feature",
    "draftOrders.headline": "Draft Orders:",
    "draftOrders.headlineBold": "The Magic Behind LiveDealz",
    "draftOrders.description": "Shopify Draft Orders are the heart of our reservation logic. They enable atomic inventory security – without complicated workarounds.",
    "draftOrders.whatBadge": "What Are Draft Orders?",
    "draftOrders.whatTitle": "Shopify's Native Reservation Feature",
    "draftOrders.whatDescription": "Draft Orders are order drafts in Shopify that reserve inventory before the customer pays. LiveDealz uses this native feature for secure live sales.",
    "draftOrders.what1.title": "Order Draft",
    "draftOrders.what1.description": "A Draft Order is like an order that hasn't been completed yet – but the inventory is already reserved.",
    "draftOrders.what2.title": "Inventory Locked",
    "draftOrders.what2.description": "Once a Draft Order is created, the variant is no longer available for other buyers.",
    "draftOrders.what3.title": "Automatic Release",
    "draftOrders.what3.description": "If the customer doesn't pay within the deadline, the inventory is automatically released.",
    "draftOrders.howBadge": "How It Works",
    "draftOrders.howTitle": "The LiveDealz Draft Order Workflow",
    "draftOrders.howDescription": "From reservation to order in 5 steps – fully automated and risk-free.",
    "draftOrders.step1.title": "Customer Reserves",
    "draftOrders.step1.description": "During your livestream or via stories, the customer reserves a product with their customer number.",
    "draftOrders.step2.title": "Draft Order Created",
    "draftOrders.step2.description": "LiveDealz automatically creates a Shopify Draft Order. The inventory is immediately reserved.",
    "draftOrders.step3.title": "Inventory Secured",
    "draftOrders.step3.description": "The variant is no longer available for other buyers. No double sales possible.",
    "draftOrders.step4.title": "Checkout Link Sent",
    "draftOrders.step4.description": "The customer receives a payment link. You decide when it's sent.",
    "draftOrders.step5.title": "Payment or Release",
    "draftOrders.step5.description": "If the customer pays, the order is completed. If not, the inventory is automatically released.",
    "draftOrders.benefitsBadge": "Benefits",
    "draftOrders.benefitsTitle": "Why Draft Orders Are a Game-Changer",
    "draftOrders.benefit1.title": "No Overselling",
    "draftOrders.benefit1.description": "Inventory is atomically reserved. Two customers can never reserve the same product.",
    "draftOrders.benefit2.title": "Automatic Release",
    "draftOrders.benefit2.description": "Non-payers no longer block your inventory. After the deadline, it's automatically released.",
    "draftOrders.benefit3.title": "Instant Reservation",
    "draftOrders.benefit3.description": "Reservation happens in milliseconds. Your customers see immediately if a product is available.",
    "draftOrders.benefit4.title": "Collect Now, Pay Later",
    "draftOrders.benefit4.description": "Customers can collect over several days and pay everything at once at the end.",
    "draftOrders.benefit5.title": "Native Shopify Feature",
    "draftOrders.benefit5.description": "No third parties, no complicated workarounds. Draft Orders are part of Shopify.",
    "draftOrders.benefit6.title": "ERP Compatible",
    "draftOrders.benefit6.description": "Your existing system continues running. Draft Orders integrate seamlessly into your workflow.",
    "draftOrders.compareTitle": "The Difference Matters",
    "draftOrders.compareDescription": "Compare manual processes with LiveDealz Draft Order logic.",
    "draftOrders.compareBefore": "Manual",
    "draftOrders.compareAfter": "With LiveDealz",
    "draftOrders.compare.feature1": "Inventory Reservation",
    "draftOrders.compare.before1": "Excel spreadsheet",
    "draftOrders.compare.after1": "Automatic",
    "draftOrders.compare.feature2": "Overselling Protection",
    "draftOrders.compare.before2": "Not available",
    "draftOrders.compare.after2": "100% guaranteed",
    "draftOrders.compare.feature3": "Atomic Reservation",
    "draftOrders.compare.feature4": "Non-Payer Handling",
    "draftOrders.compare.before4": "Manual check",
    "draftOrders.compare.after4": "Auto-release",
    "draftOrders.compare.feature5": "ERP Integration",
    "draftOrders.relatedTitle": "Learn More",
    "draftOrders.related1.title": "Shopify Integration",
    "draftOrders.related1.description": "Learn how LiveDealz works seamlessly with your store.",
    "draftOrders.related2.title": "LiveDealz vs. Manual",
    "draftOrders.related2.description": "Detailed comparison: What do you really save?",
    "draftOrders.related3.title": "TikTok & Instagram Live",
    "draftOrders.related3.description": "How to use Draft Orders in your livestreams.",
    "draftOrders.ctaTitle": "Ready for Secure Live Sales?",
    "draftOrders.ctaDescription": "Experience how Draft Orders revolutionize your live shopping – without overselling, without stress.",
  },
  no: {
    // Promo Banner
    "promo.starterOffer": "🎉 Starter-plan for kun €79/måned – Tilbudet gjelder til 31.12.2025!",

    // Navbar
    "nav.features": "Funksjoner",
    "nav.draftOrders": "Draft Orders",
    "nav.benefits": "Fordeler",
    "nav.pricing": "Priser",
    "nav.b2b": "B2B",
    "nav.faq": "FAQ",
    "nav.contact": "Kontakt",
    "nav.bookDemo": "Bestill demo",

    // Hero
    "hero.badge": "Community Commerce Engine",
    "hero.headline1": "Reserver.",
    "hero.headline2": "Samle.",
    "hero.headline3": "Betal.",
    "hero.subheadline": "Maksimalt salg. Minimalt arbeid.",
    "hero.description1": "Enten det er livestream, WhatsApp-story eller samleaksjon –",
    "hero.description1Bold": " ett system, én lagerbeholdning, ingen kaos.",
    "hero.description2": "LiveDealz kobler live-shopping, stories og samleaksjoner sammen. Kunder reserverer produkter under streamen eller stories, samler over flere dager og betaler senere med ett klikk i Shopify-checkout.",
    "hero.cta1": "Bestill demo nå",
    "hero.cta2": "Se funksjonsoversikt",
    "hero.merchants": "100+ aktive forhandlere",
    "hero.reservationConfirmed": "Reservasjon bekreftet",
    "hero.stockSecured": "Lager sikret ✓",
    "hero.viewers": "seere",
    "hero.imageAlt": "Forhandler under live-shopping med LiveDealz",

    // Problem Section
    "problem.badge": "Problemet",
    "problem.headline": "Høres dette kjent ut?",
    "problem.description": "Du viser produkter i livestream eller WhatsApp-stories. Kunder kommenterer, sender meldinger, deler skjermbilder. I bakgrunnen:",
    "problem.descriptionBold": " Excel-ark, WhatsApp-kaos, manuelt papirarbeid.",
    "problem.conclusion": "Dette skalerer ikke. Hver måned koster det deg",
    "problem.conclusionBold": "omsetning og nerver.",
    "problem.item1.title": "WhatsApp & kommentar-kaos",
    "problem.item1.description": "Kunder skriver 'Jeg vil ha!', sender skjermbilder, kommenterer under streams. Du drukner i meldinger.",
    "problem.item2.title": "Excel & papirkaos",
    "problem.item2.description": "Reservasjoner i Excel-ark, WhatsApp-chatter og på papirlapper. Ingen system, ingen oversikt.",
    "problem.item3.title": "Oversalg & dobbeltbookinger",
    "problem.item3.description": "To kunder reserverer samme produkt. En går tomhendt – og er frustrert.",
    "problem.item4.title": "Ikke-betalere blokkerer lager",
    "problem.item4.description": "Kunder reserverer men betaler aldri. Lageret ditt er blokkert, andre kjøpere går glipp av det.",
    "problem.item5.title": "Timer på fakturaer",
    "problem.item5.description": "Etter streamen: timers arbeid med å manuelt sette sammen alle bestillinger.",
    "problem.item6.title": "Ikke skalerbart",
    "problem.item6.description": "Flere kunder betyr mer kaos. Vekst blir et problem i stedet for en mulighet.",

    // Solution Section
    "solution.badge": "Løsningen",
    "solution.headline": "Hva LiveDealz gjør",
    "solution.description": "LiveDealz kobler Shopify-butikken din med live- og sosiale kanaler. Ett system for alt – TikTok, Instagram, WhatsApp, Discord, Telegram.",
    "solution.storefront.title": "Butikkfront-modus",
    "solution.storefront.description": "Kunder blar i butikken din selvstendig under eller etter streams og ser en spesiell LiveDealz- eller kampanjesamling.",
    "solution.storefront.item1": "Dedikert samling i Shopify-butikk",
    "solution.storefront.item2": "Kunder kan bla og bestille selvstendig",
    "solution.storefront.item3": "Lager reservert i sanntid",
    "solution.storefront.item4": "Brukbart parallelt med stream eller asynkront",
    "solution.dashboard.title": "Selger-dashboard-modus",
    "solution.dashboard.description": "Du er live på TikTok eller mottar WhatsApp-story-kommentarer. Kunder har et kundenummer – du reserverer med skanning eller klikk.",
    "solution.dashboard.item1": "Skriv inn kundenummer, skann strekkode",
    "solution.dashboard.item2": "Reservasjon opprettes umiddelbart",
    "solution.dashboard.item3": "Lager blokkeres automatisk",
    "solution.dashboard.item4": "Ideelt for interaktive livestreams",
    "solution.atomic.title": "Atomær lagerlogikk",
    "solution.atomic.description": "Når reservert, er varianten låst. Ingen dobbeltsalg, ingen overbooking.",
    "solution.collect.title": "Samle nå, betal senere",
    "solution.collect.description": "Kunder samler mandag til fredag, checkout-lenker sendes ut lørdag.",
    "solution.shopify.title": "Sømløs Shopify-integrasjon",
    "solution.shopify.description": "Native checkout, utkastordrer i Shopify. Butikken din fortsetter som vanlig.",
    "solution.release.title": "Automatisk frigjøring",
    "solution.release.description": "Hvis en kunde ikke betaler, frigjøres reservasjonen etter en definert tid.",
    "solution.whatsapp.title": "Perfekt for WhatsApp & Instagram Stories",
    "solution.whatsapp.description": "Bruk WhatsApp-stories som ditt showroom. Hver kontakt har et kundenummer. Konverter kommentarer og henvendelser til reservasjoner via dashboardet. Kunder kan fortsette å handle etter streamen eller stories – alt kjører i samme system.",

    // Features Section
    "features.badge": "Funksjoner",
    "features.headline": "Alt du trenger for vellykket",
    "features.headlineBold": "live-salg",
    "features.headlineEnd": "",
    "features.description": "Fra reservasjon til betaling – LiveDealz automatiserer hele salgsprosessen din.",
    "features.item1.title": "Sanntidsreservasjoner",
    "features.item1.description": "Kunder reserverer produkter live under streamen din. Betaling skjer senere gjennom integrert Shopify-checkout.",
    "features.item2.title": "Individuelle kundenumre",
    "features.item2.description": "Hver kunde får automatisk sitt eget nummer. Reservasjoner tildeles tydelig – ingen forvekslinger.",
    "features.item3.title": "Smart lagerreservasjon",
    "features.item3.description": "Produkter låses automatisk ved reservasjon. Hvis en kunde ikke betaler, frigjøres lageret.",
    "features.item4.title": "Enkel betjening",
    "features.item4.description": "Skann produkter via strekkode og tilordne dem til kundenumre. Reservasjon på sekunder – direkte fra smarttelefonen.",
    "features.item5.title": "Automatiske påminnelser",
    "features.item5.description": "Kunder blir påminnet om åpne bestillinger. Ikke-betalere kan automatisk blokkeres for fremtidige reservasjoner.",
    "features.item6.title": "Spesielle livestream-priser",
    "features.item6.description": "Tildel individuelle priser under streamen. Fleksibelt og uten begrensninger – perfekt for live-tilbud.",
    "features.item7.title": "Sømløs integrasjon",
    "features.item7.description": "Din eksisterende butikk fortsetter som vanlig. Selg samtidig i nettbutikk og livestream – alt synkronisert.",
    "features.item8.title": "GDPR-kompatibel & sikker",
    "features.item8.description": "Dataene dine er trygge hos oss. Servere i Tyskland, høyeste sikkerhetsstandarder og full GDPR-overholdelse.",

    // Use Cases Section
    "useCases.badge": "Brukstilfeller",
    "useCases.headline": "Riktig løsning for hver salgskanal",
    "useCases.description": "Uansett hvordan du selger – LiveDealz tilpasser seg arbeidsflyten din.",
    "useCases.case1.title": "TikTok & Instagram Live-selgere",
    "useCases.case1.step1": "Du presenterer produkter i livestreamen",
    "useCases.case1.step2": "Seere gir kundenummeret sitt, du skanner produkter",
    "useCases.case1.step3": "Andre kan handle parallelt i butikken din",
    "useCases.case1.step4": "Ingen oversalg, mindre stress, mer omsetning",
    "useCases.case2.title": "WhatsApp Story-forhandlere",
    "useCases.case2.step1": "Produkter vises i WhatsApp-status/stories",
    "useCases.case2.step2": "Kunder svarer med 'Jeg vil ha' på storyen",
    "useCases.case2.step3": "Du legger inn produktet med kundenummer i dashboardet",
    "useCases.case2.step4": "Samling over flere dager, alle checkout-lenker sendes til slutt",
    "useCases.case3.title": "Community-samleaksjoner",
    "useCases.case3.step1": "Du har en Discord-, Telegram- eller WhatsApp-gruppe",
    "useCases.case3.step2": "Kampanje: 'Vi samler bestillinger til fredag'",
    "useCases.case3.step3": "LiveDealz konsoliderer alle reservasjoner",
    "useCases.case3.step4": "Alle utkastordrer genereres automatisk til slutt",
    "useCases.case4.title": "B2B & grossist-scenario",
    "useCases.case4.step1": "Flere forhandlere kan reservere samtidig",
    "useCases.case4.step2": "Sanntids lagervisning – først til mølla",
    "useCases.case4.step3": "Fleksibel fakturering: lever først, fakturer senere",
    "useCases.case4.step4": "Ingen kompliserte forespørsler via e-post eller Excel",

    // Origin Story Section
    "origin.badge": "Vår historie",
    "origin.headline": "Født fra",
    "origin.headlineBold": "praksis",
    "origin.description": "LiveDealz er ikke teori – det er svaret på virkelige problemer vi selv opplevde.",
    "origin.step": "Trinn",
    "origin.step1.title": "Stormen",
    "origin.step1.description": "LSQ24, en forhandler spesialisert på live-shopping, opplevde eksplosiv vekst. Men med suksessen kom problemene.",
    "origin.step2.title": "Overbelastningen",
    "origin.step2.description": "Systemet kollapset under vekten av nye reservasjoner. Excel-ark, WhatsApp-meldinger og manuelle prosesser førte til kaos.",
    "origin.step3.title": "Ikke-betalerne",
    "origin.step3.description": "Kunder reserverte men betalte ikke. Lager var blokkert, omsetning tapt. Oversikten var helt borte.",
    "origin.step4.title": "Løsningen",
    "origin.step4.description": "Fra denne nøden ble LiveDealz født – utviklet av forhandlere for forhandlere. En løsning som løser alle problemer samtidig.",
    "origin.conclusion.title": "Av forhandlere. For forhandlere.",
    "origin.conclusion.description1": "Vi vet nøyaktig hva du trenger – fordi vi selv var i live-shopping. LiveDealz bruker Shopifys native reservasjonsfunksjon for å låse lager i en definert periode. Hvis en kunde ikke betaler, frigjøres lageret automatisk og kunden blokkeres for fremtidige reservasjoner.",
    "origin.conclusion.description2": "Det beste: Din eksisterende butikk fortsetter som vanlig. Ingen forstyrrelse av ERP-systemer, ingen kompliserte endringer. Selg samtidig via nettbutikk og livestream – alt perfekt synkronisert.",

    // Pricing Section
    "pricing.pioneerBadge": "Eksklusivt tilbud",
    "pricing.pioneerTitle": "Bli en av våre pionerkunder!",
    "pricing.pioneerDescription": "Vi er nye på markedet og søker engasjerte partnere. Dra nytte av attraktive inngangspriser!",
    "pricing.badge": "Priser",
    "pricing.headline": "Transparente priser for enhver bedrift",
    "pricing.description": "Velg riktig plan for din live-shopping-bedrift. Ingen skjulte kostnader.",
    "pricing.monthly": "Månedlig",
    "pricing.yearly": "Årskontrakt",
    "pricing.savingsNote": "Spesielle vilkår for nye kunder*",
    "pricing.savingsDisclaimer": "(*) Rabatterte priser gjelder i 12 måneder for opprinnelig bestilte brukere.",
    "pricing.popular": "Mest populær",
    "pricing.limitedTime": "Begrenset",
    "pricing.startingFrom": "Fra",
    "pricing.custom": "(tilpasset)",
    "pricing.perMonth": "/ måned",
    "pricing.billedYearly": "Faktureres årlig:",
    "pricing.scopeTitle": "Omfang",
    "pricing.supportTitle": "Support",
    "pricing.starter.name": "Starter",
    "pricing.starter.description": "Perfekt for nybegynnere og testfasen",
    "pricing.starter.cta": "Kom i gang",
    "pricing.starter.features.1": "Sanntidsreservasjoner",
    "pricing.starter.features.2": "Individuelle kundenumre",
    "pricing.starter.features.3": "Variantfiltrering (størrelse, farge)",
    "pricing.starter.features.4": "Shopify-integrasjon & strekkodeskanning",
    "pricing.starter.scope.1": "Ubegrensede brukere",
    "pricing.starter.scope.2": "Ubegrensede produkter",
    "pricing.starter.scope.3": "300 reservasjoner/måned",
    "pricing.starter.support.1": "E-post-support",
    "pricing.pro.name": "Pro",
    "pricing.pro.description": "For semi-profesjonelle til profesjonelle forhandlere",
    "pricing.pro.cta": "Oppgrader nå",
    "pricing.pro.features.1": "Alt i Starter +",
    "pricing.pro.features.2": "B2B-funksjoner (spesialpriser)",
    "pricing.pro.features.3": "Automatiske betalingspåminnelser",
    "pricing.pro.features.4": "Blokkering av ikke-betalere",
    "pricing.pro.features.5": "Live-dashboard for statistikk",
    "pricing.pro.scope.1": "Ubegrensede brukere",
    "pricing.pro.scope.2": "Ubegrensede produkter",
    "pricing.pro.scope.3": "Ubegrensede reservasjoner",
    "pricing.pro.support.1": "Priority-support (Slack/WhatsApp)",
    "pricing.pro.support.2": "Personlig onboarding-økt",
    "pricing.enterprise.name": "Enterprise",
    "pricing.enterprise.description": "For store merker og multi-kanal-operatører",
    "pricing.enterprise.cta": "Kontakt oss",
    "pricing.enterprise.features.1": "Alt i Pro +",
    "pricing.enterprise.features.2": "Tilpassede integrasjoner (Xentral, ERP)",
    "pricing.enterprise.features.3": "Flerspråklig støtte",
    "pricing.enterprise.features.4": "White-label-alternativ",
    "pricing.enterprise.features.5": "SLA/Uptime-garanti",
    "pricing.enterprise.scope.1": "Ubegrensede brukere",
    "pricing.enterprise.scope.2": "Ubegrensede produkter",
    "pricing.enterprise.scope.3": "Ubegrensede reservasjoner",
    "pricing.enterprise.support.1": "Dedikert kontoansvarlig",
    "pricing.enterprise.support.2": "24/7 premium-support",
    "pricing.enterprise.support.3": "Individuelle opplæringer",
    "pricing.testimonial": "\"LiveDealz var et fullstendig gjennombrudd for oss! Vi sparte enorme mengder tid, reduserte feil drastisk og økte omsetningen merkbart. Det føles som om vi har gjenoppfunnet bedriften vår fullstendig!\"",
    "pricing.testimonialAuthor": "Ali Kaawar",
    "pricing.testimonialRole": "CEO @ LSQ24",

    // FAQ Section
    "faq.headline": "Ofte stilte spørsmål",
    "faq.q1": "Hva er LiveDealz og hvordan fungerer det?",
    "faq.a1": "LiveDealz er en plattform som lar deg selge produkter i sanntid under livestreamen din. Kunder kan reservere varer uten å forlate streamen eller betale umiddelbart. Reservasjoner administreres automatisk og kan betales samlet på et senere tidspunkt.",
    "faq.q2": "Hvordan hjelper LiveDealz meg med å administrere salget mitt?",
    "faq.a2": "LiveDealz gir en sentral oversikt over alle reservasjoner og bestillinger. Du kan spore lager i sanntid, administrere kundehenvendelser og få betalinger behandlet automatisk. Vår AI filtrerer spam-reservasjoner og optimaliserer lageret ditt.",
    "faq.q3": "Kan jeg bruke LiveDealz når jeg ikke er live?",
    "faq.a3": "Ja! Kunder kan fortsette å reservere og handle etter livestreamen. Produktene dine forblir tilgjengelige og salgsprosessen fortsetter automatisk – maksimerer omsetningen din døgnet rundt.",
    "faq.q4": "Hvordan integreres bestillinger i Shopify?",
    "faq.a4": "LiveDealz integreres sømløst i Shopify-butikken din. Alle reservasjoner og bestillinger synkroniseres automatisk, slik at du beholder en enhetlig oversikt og ingen manuell dataregistrering er nødvendig.",
    "faq.q5": "Hvor sikre er dataene mine med LiveDealz?",
    "faq.a5": "Dataene dine er godt beskyttet hos oss. Serverne våre er lokalisert i Tyskland og er GDPR-kompatible. Vi bruker moderne krypteringsteknologier og gjennomfører regelmessige sikkerhetsrevisjoner.",

    // Tech Trust Section
    "tech.headline": "Teknologi du kan stole på",
    "tech.description": "Moderne infrastruktur for pålitelig ytelse – selv under høy belastning.",
    "tech.item1.title": "Hendelsesdrevet arkitektur",
    "tech.item1.description": "Webhooks fra Shopify behandles i sanntid. Hver lagerendring synkroniseres umiddelbart.",
    "tech.item2.title": "Skalerbar købehandling",
    "tech.item2.description": "Behandling via køer muliggjør høy belastning til lave faste kostnader for forhandlere.",
    "tech.item3.title": "Privacy by Design",
    "tech.item3.description": "Kun minimale IDer lagres. Ingen personlige data i systemet vårt.",
    "tech.item4.title": "Servere i EU",
    "tech.item4.description": "GDPR-kompatibel. All data behandles på servere i EU.",

    // CTA Section
    "cta.headline": "Maksimer din live-shopping-suksess",
    "cta.description": "Med LiveDealz tar du bedriften din til neste nivå. Øk omsetningen gjennom sanntidsreservasjoner, automatiser prosessene dine og skap en sømløs handleopplevelse for kundene dine.",
    "cta.button1": "Få din prøvemåned",
    "cta.button2": "Kontakt oss",

    // Contact Section
    "contact.badge": "Kontakt",
    "contact.headline": "Klar til å komme i gang?",
    "contact.description": "La oss diskutere hvordan LiveDealz kan ta live-shopping-bedriften din til neste nivå. Bestill en gratis demo eller kontakt oss direkte.",
    "contact.emailLabel": "E-post",
    "contact.responseLabel": "Svartid",
    "contact.responseTime": "Innen 24 timer",

    // Footer
    "footer.tagline": "Plattformen for live-, story- og samlesalg uten kaos.",
    "footer.description": "Reserver. Samle. Betal. Ett system, én lagerbeholdning – for TikTok, Instagram, WhatsApp og community-salg.",
    "footer.product": "Produkt",
    "footer.features": "Funksjoner",
    "footer.useCases": "Brukstilfeller",
    "footer.pricing": "Priser",
    "footer.faq": "FAQ",
    "footer.resources": "Ressurser",
    "footer.bookDemo": "Bestill demo",
    "footer.contact": "Kontakt",
    "footer.legal": "Juridisk",
    "footer.imprint": "Impressum",
    "footer.privacy": "Personvern",
    "footer.terms": "Vilkår",
    "footer.copyright": "Alle rettigheter reservert.",
    "footer.businessOnly": "Merk: Tilbudene og innholdet på denne nettsiden er utelukkende beregnet for bedrifter og kommersielle kunder.",

    // B2B Page
    "b2b.badge": "LiveDealz for B2B",
    "b2b.painPoint": "Slutt på oversalgsrisiko og manuell bestillingsflaskehals.",
    "b2b.painPointHighlight": "Penger elsker hastighet.",
    "b2b.headline": "Endelig engros uten risiko:",
    "b2b.headlineHighlight": "Sikret lager gjennom sanntidsreservasjon",
    "b2b.subheadline": "Garantert lagerreservasjon i bestillingsøyeblikket. Ingen oversalg, ingen forespørsler, ingen tapte bestillinger.",
    "b2b.cta": "Bestill demo: Opplev lagersikkerhet i sanntid",
    "b2b.problemTitle": "Du kjenner denne risikoen",
    "b2b.problemDescription": "Dine forhandlere bestiller via e-post eller Excel. Konstante forespørsler om tilgjengelighet, manuelle lagerkontroller og kaotisk kommunikasjon koster tid og penger.",
    "b2b.problemConclusion": "Og det verste: Når flere forhandlere bestiller samtidig, overselger du – og må kansellere. Tapt tillit, tapt omsetning.",
    "b2b.solutionBadge": "Løsningen",
    "b2b.solutionTitle": "Garantert lagersikkerhet med",
    "b2b.solutionDescription": "Atomære reservasjoner i bestillingsøyeblikket. Dine forhandlere ser bare hva som er tilgjengelig – og er garantert å få det de bestiller.",
    "b2b.benefit1.title": "Atomær reservasjonsgaranti",
    "b2b.benefit1.description": "Varene dine bookes permanent ut av lageret i bestillingsøyeblikket. Ingen mer oversalg. Forhandlere ser bare hva de er garantert å motta.",
    "b2b.benefit2.title": "Sanntidstilgjengelighet",
    "b2b.benefit2.description": "Lager reserveres permanent i bestillingsøyeblikket. Umiddelbart synlig hva som er tilgjengelig – ingen flere forespørsler nødvendig.",
    "b2b.benefit3.title": "Markedsplassopplevelse",
    "b2b.benefit3.description": "Presenter sortimentet ditt som en digital markedsplass. Forhandlere velger hva og hvor mye de vil kjøpe – først til mølla.",
    "b2b.benefit4.title": "Fleksibel fakturering",
    "b2b.benefit4.description": "Lever først, fakturer senere. LiveDealz samler alle bestillinger og du bestemmer når du fakturerer.",
    "b2b.benefit5.title": "Fremtidssikker B2B-plattform",
    "b2b.benefit5.description": "Vi bruker Shopify som ryggrad fordi det tilbyr størst grensesnittdekning til alle ERP-systemer. Bruk bevist og mobil teknologi for engroshandelen din.",
    "b2b.benefit6.title": "Full fleksibilitet",
    "b2b.benefit6.description": "Bestillinger kan legges inn når som helst, hvor som helst. Med Shopify som base får forhandlerne dine en native, mobil kjøpsopplevelse – på PC, nettbrett eller telefon.",
    "b2b.speedTitle": "Hastighetsfordelen teller",
    "b2b.speedDescription": "Ja, Shopify koster ca. €30-40/måned. Men hvor mye penger taper du per måned gjennom manuelt kaos, ineffektive forespørsler og kansellerte oversalg?",
    "b2b.speedConclusion": "LiveDealz bruker Shopify for å gi deg hastigheten og sikkerheten engroshandelen din trenger.",
    "b2b.useCasesBadge": "Brukstilfeller",
    "b2b.useCasesTitle": "Perfekt for din",
    "b2b.useCasesTitleHighlight": "B2B-distribusjon",
    "b2b.useCasesDescription": "Enten du er grossist, produsent eller importør – LiveDealz tilpasser seg forretningsmodellen din og gjør B2B-bestillinger sikre og effektive.",
    "b2b.useCase1": "Grossister med regelmessige bestillingsrunder",
    "b2b.useCase2": "Produsenter med direktesalg til forhandlere",
    "b2b.useCase3": "Showroom-salg med live-presentasjon",
    "b2b.useCase4": "Sesongbaserte kolleksjonspresentasjoner",
    "b2b.useCase5": "B2B-markedsplasser og messer",
    "b2b.howItWorksTitle": "Slik fungerer det",
    "b2b.step1.title": "Presenter produkter",
    "b2b.step1.description": "Vis sortimentet ditt live eller på en permanent bestillingsside.",
    "b2b.step2.title": "Forhandlere bestiller selv",
    "b2b.step2.description": "Dine forhandlere velger produkter og mengder – i sanntid og selvstendig.",
    "b2b.step3.title": "Lager garantert reservert",
    "b2b.step3.description": "I bestillingsøyeblikket bookes varene permanent ut – ingen dobbeltsalg mulig.",
    "b2b.step4.title": "Faktura etter levering",
    "b2b.step4.description": "Du bestemmer når bestillingen faktureres.",
    "b2b.ctaTitle": "Klar for risikofri B2B-distribusjon?",
    "b2b.ctaDescription": "Opplev hvordan LiveDealz eliminerer oversalg og revolusjonerer engroshandelen din med garantert sanntidsreservasjon.",

    // Draft Orders Feature Page
    "draftOrders.seo.title": "Draft Orders – Hjertet av LiveDealz | Shopify Reservasjonslogikk",
    "draftOrders.seo.description": "Lær hvordan LiveDealz bruker Shopify Draft Orders for å muliggjøre atomære reservasjoner. Ingen oversalg, automatisk lagerfrigjøring.",
    "draftOrders.badge": "Kjernefunksjon",
    "draftOrders.headline": "Draft Orders:",
    "draftOrders.headlineBold": "Magien bak LiveDealz",
    "draftOrders.description": "Shopify Draft Orders er hjertet i reservasjonslogikken vår. De muliggjør atomær lagersikkerhet – uten kompliserte omveier.",
    "draftOrders.whatBadge": "Hva er Draft Orders?",
    "draftOrders.whatTitle": "Shopifys native reservasjonsfunksjon",
    "draftOrders.whatDescription": "Draft Orders er bestillingsutkast i Shopify som reserverer lager før kunden betaler. LiveDealz bruker denne native funksjonen for sikre live-salg.",
    "draftOrders.what1.title": "Bestillingsutkast",
    "draftOrders.what1.description": "En Draft Order er som en bestilling som ikke er fullført ennå – men lageret er allerede reservert.",
    "draftOrders.what2.title": "Lager låst",
    "draftOrders.what2.description": "Når en Draft Order opprettes, er varianten ikke lenger tilgjengelig for andre kjøpere.",
    "draftOrders.what3.title": "Automatisk frigjøring",
    "draftOrders.what3.description": "Hvis kunden ikke betaler innen fristen, frigjøres lageret automatisk.",
    "draftOrders.howBadge": "Slik fungerer det",
    "draftOrders.howTitle": "LiveDealz Draft Order-arbeidsflyten",
    "draftOrders.howDescription": "Fra reservasjon til bestilling i 5 trinn – helautomatisk og risikofri.",
    "draftOrders.step1.title": "Kunde reserverer",
    "draftOrders.step1.description": "Under livestreamen din eller via stories reserverer kunden et produkt med kundenummeret sitt.",
    "draftOrders.step2.title": "Draft Order opprettes",
    "draftOrders.step2.description": "LiveDealz oppretter automatisk en Shopify Draft Order. Lageret reserveres umiddelbart.",
    "draftOrders.step3.title": "Lager sikret",
    "draftOrders.step3.description": "Varianten er ikke lenger tilgjengelig for andre kjøpere. Ingen dobbeltsalg mulig.",
    "draftOrders.step4.title": "Checkout-lenke sendes",
    "draftOrders.step4.description": "Kunden mottar en betalingslenke. Du bestemmer når den sendes.",
    "draftOrders.step5.title": "Betaling eller frigjøring",
    "draftOrders.step5.description": "Hvis kunden betaler, fullføres bestillingen. Hvis ikke, frigjøres lageret automatisk.",
    "draftOrders.benefitsBadge": "Fordeler",
    "draftOrders.benefitsTitle": "Hvorfor Draft Orders er en game-changer",
    "draftOrders.benefit1.title": "Ingen oversalg",
    "draftOrders.benefit1.description": "Lager reserveres atomært. To kunder kan aldri reservere samme produkt.",
    "draftOrders.benefit2.title": "Automatisk frigjøring",
    "draftOrders.benefit2.description": "Ikke-betalere blokkerer ikke lenger lageret ditt. Etter fristen frigjøres det automatisk.",
    "draftOrders.benefit3.title": "Umiddelbar reservasjon",
    "draftOrders.benefit3.description": "Reservasjon skjer på millisekunder. Kundene dine ser umiddelbart om et produkt er tilgjengelig.",
    "draftOrders.benefit4.title": "Samle nå, betal senere",
    "draftOrders.benefit4.description": "Kunder kan samle over flere dager og betale alt på en gang til slutt.",
    "draftOrders.benefit5.title": "Native Shopify-funksjon",
    "draftOrders.benefit5.description": "Ingen tredjeparter, ingen kompliserte omveier. Draft Orders er en del av Shopify.",
    "draftOrders.benefit6.title": "ERP-kompatibel",
    "draftOrders.benefit6.description": "Det eksisterende systemet ditt fortsetter å kjøre. Draft Orders integreres sømløst i arbeidsflyten din.",
    "draftOrders.compareTitle": "Forskjellen betyr noe",
    "draftOrders.compareDescription": "Sammenlign manuelle prosesser med LiveDealz Draft Order-logikk.",
    "draftOrders.compareBefore": "Manuelt",
    "draftOrders.compareAfter": "Med LiveDealz",
    "draftOrders.compare.feature1": "Lagerreservasjon",
    "draftOrders.compare.before1": "Excel-ark",
    "draftOrders.compare.after1": "Automatisk",
    "draftOrders.compare.feature2": "Oversalgsbeskyttelse",
    "draftOrders.compare.before2": "Ikke tilgjengelig",
    "draftOrders.compare.after2": "100% garantert",
    "draftOrders.compare.feature3": "Atomær reservasjon",
    "draftOrders.compare.feature4": "Håndtering av ikke-betalere",
    "draftOrders.compare.before4": "Manuell sjekk",
    "draftOrders.compare.after4": "Auto-frigjøring",
    "draftOrders.compare.feature5": "ERP-integrasjon",
    "draftOrders.relatedTitle": "Lær mer",
    "draftOrders.related1.title": "Shopify-integrasjon",
    "draftOrders.related1.description": "Lær hvordan LiveDealz fungerer sømløst med butikken din.",
    "draftOrders.related2.title": "LiveDealz vs. Manuelt",
    "draftOrders.related2.description": "Detaljert sammenligning: Hva sparer du egentlig?",
    "draftOrders.related3.title": "TikTok & Instagram Live",
    "draftOrders.related3.description": "Hvordan bruke Draft Orders i livestreamene dine.",
    "draftOrders.ctaTitle": "Klar for sikre live-salg?",
    "draftOrders.ctaDescription": "Opplev hvordan Draft Orders revolusjonerer live-shoppingen din – uten oversalg, uten stress.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "de";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.de] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
